### PR TITLE
restful burndown chart

### PR DESCRIPTION
**Pull request by ErikLupical**
A pull request for the burndown chart to find or help solves issues. Added a burndown chart that displays estimate history as a chart using chart js.

### CODE REVIEW

**Review by Jangsoodlor — CHANGES_REQUESTED** [review]
- The event seems to be plotting a new green bar when I select events from the side by. This seems to be caused by `processEventsData` function in your `burndown.js` returning a "box" chart. You might want to do something like in `processTasksData` to plot an arbitrary line though.

**Comment by Jangsoodlor** [comment]
mis-clicked sorry.

**Comment by Jangsoodlor** [comment]
@ErikLupical Pls add tests and make sure that your code passed the ES Linter. Otherwise, we can't really start the PR review.

**Comment by Jangsoodlor** [comment]
The task seems to be not showing when there are estimate history objects before today.

image
image


How to reproduce:
1. create an EstimateHistory object and set the date to be before today.
2. create a task and set the due date to today.

**Comment by ErikLupical** [comment]
> The task seems to be not showing when there are estimate history objects before today.
> 
> image image
> 
> How to reproduce:
> 
> 1. create an EstimateHistory object and set the date to be before today.
> 2. create a task and set the due date to today.

did you set the time_remaining of the task to a number > 0 when you created it?

**Comment by Jangsoodlor** [comment]
> a number > 0 when you created it?

image

**Comment by Jangsoodlor** [comment]
> This better not be a scroll bar for the chart itself. I think we have already had a discussion about this.
> 
> Do not test my patience.

This is one of the reasons why a scroll bar is not a good idea. Good luck scrolling that lol
image

**Comment by BioB3** [comment]
> The task seems to be not showing when there are estimate history objects before today.
> 
> image image
> 
> How to reproduce:
> 
> 1. create an EstimateHistory object and set the date to be before today.
> 2. create a task and set the due date to today.

I think this is due to how he filters tasks and events, it currently shows only tasks and events before the end of the velocity trend line. In your picture, there is no velocity trend line because the slope is positive resulting in no tasks and events loaded.

**Comment by KhunakornP** [comment]
deploy_at_5_on_friday_sure

**Comment by Jangsoodlor** [comment]
The quick (and easy) way to fix the "9990 years bug" and the "1-year-old taskboard where the user has to scroll really long to get to today" is to implement what Timmy has repeatedly suggested over the past 3 weeks, which is setting the boundary on the graph's x-axis to be [x days before today, y days after today].

**Comment by Jangsoodlor** [comment]
The data aggregation on the year works fine.  You've done a good job! But it seems like "today" is still not shown in the "days" view.
days
You could fix it to be more like the "year" view tho
years


**BUT** I have a question on the "months" views.
image
Yes, it's _technically_ correct that the tasks might end in March. But it's March 2052. This could be quite misleading for users.

I appreciate the extra feature, but could you explain what the user can get from this?

**Comment by Jangsoodlor** [comment]
Since it seems like the chart is nearly done, I'll point out some minor errors that I encountered
- Please re-check your docstrings. For example, line 11 in `test_burndown_views.py` is erroneously wrong.
- I see that you're trying to implement some sort of docstrings in JavaScript like `// par: String, ret: Number`. While not required, it doesn't conform to the JS style guide we agreed on. Either you go change that or convince @BioB3 to change the style guide.

**Comment by KhunakornP** [comment]
> The data aggregation on the year works fine. You've done a good job! years
> 
> But it seems like "today" is still not shown in the "days" view. days You could fix it to be more like the "year" view tho
> 
> **HOWEVER,** I have a question on the "months" views. image Yes, it's _technically_ correct that the tasks might end in March. But it's March 2052. This could be quite misleading for users.
> 
> I think @KhunakornP may appreciate the extra feature, but I don't understand what the user could get from this particular view that's implemented in this way. Could you clarify why the user might need it?

If you WANT to make a new feature, at least make sure it works.
Also I've seen the latest commit, can you please tell me why not being able to select the month when the data spans multiple years is intuitive.
Also while we're at it why are you even showing a burndown chart YEARS in advance.

**Comment by KhunakornP** [comment]
Ping in discord when you want me to review it. If it still doesn't make sense I'm closing this PR

**Comment by Jangsoodlor** [comment]
Also, the "dates" view is still wrong btw. It's still showing data from 2010 without "today" on my machine.

Here's how I config my test taskboard
- Creates 3 Estimate History Objects
- The first one is set in 2010, with an estimated time set to 10001 hours
- The second one was created yesterday, with an estimated time set to 10000 hours
- The last one is created today, with an estimated time set to 9999
- Due to how arithmetic works, the velocity of this chart is exactly 1 hour per day. This means that it'd take 9999 days to complete all the tasks according to the estimate. Which seems to be approximately the year 2052

**Comment by Jangsoodlor** [comment]
Or you could go in the more extreme route to test whether or not the "dates" view is limiting the amount of the data correctly.
- Create 2 estimate history objects
- One set in 1/1/1000 AD, with (9999-999) * 365 hours of estimated history
- Another one set in 31/12/9999 AD, with ((9999-999)*365) - 1 hours of estimated history
- If your computer does not explode, it means that you've successfully written the code to ONLY load the date range that matters to the user. i.e., [x days before today, y days after today].
- Because even in the previous case (2010-2052) the tab already taken 700++MB of my RAM. Having checks like this would prevent memory leak.

**Comment by ErikLupical** [comment]
> > The data aggregation on the year works fine. You've done a good job! years
> > But it seems like "today" is still not shown in the "days" view. days You could fix it to be more like the "year" view tho
> > **HOWEVER,** I have a question on the "months" views. image Yes, it's _technically_ correct that the tasks might end in March. But it's March 2052. This could be quite misleading for users.
> > I think @KhunakornP may appreciate the extra feature, but I don't understand what the user could get from this particular view that's implemented in this way. Could you clarify why the user might need it?
> 
> If you WANT to make a new feature, at least make sure it works. Also I've seen the latest commit, can you please tell me why not being able to select the month when the data spans multiple years is intuitive. Also while we're at it why are you even showing a burndown chart YEARS in advance. Seems like your just making quick fixes, How big is the sand pit now?

Would it be better if there weren't a years option?

**Comment by KhunakornP** [comment]
Would it be better if I just take over now :)

**Comment by Jangsoodlor** [comment]
> Would it be better if there weren't a year option?
It'd be nice. But if that's too hard to check for constraints, you could drop the months and years view to focus on the days view instead since that is **THE MOST IMPORTANT** to the user to plan their days ahead.

**Comment by Jangsoodlor** [comment]
Most importantly, since deployment is near there's another functionality (parent dashboard) that needs to integrate the burndown chart. I think it'd be wise to focus on the feature that matters most first, and then work on the extra feature.

Remember, you can open multiple PRs from the same branch. We've done that many times before.

**Comment by BioB3** [comment]
I don't understand why you're making quick fixes by introducing new features that cause even more problems when all you can do is add a limit to the number of days before and after, showing for up to 7 or 14 days (or any appropriate number) on both ends. I think the chart is almost done on commit 3228865, but the following commit is where the problem escalated. I think this could be fixed by finding estimate history objects within the date range from today and performing calculations based on them, if there is only one or none, then there's is no velocity. Also check the last estimate history object if there's none within the date range, so you can show the time remaining of today equal to that estimate history object. As for tasks and events filtering, I think it is better to find ones that are within the same date range you used and after today.

**Comment by Jangsoodlor** [comment]
Before you work on "extra features", please make sure that the "dates" view, which is the original feature of the burndown chart, works correctly first. It's still rendering 2010/10/10 as the first date and does not show "today" at all. Or is this an intended behaviour? If so, could you provide a justification of why the user might want to see the burndown chart from 14 years ago and not the range of date a wee bit before and after today?

image

Agile practice number 28: Code in Increments.

**Comment by Jangsoodlor** [comment]
Although I do not mind if the burndown chart takes a few more days to implement "basic" functionality, @KhunakornP, who is working on the parent dashboard that needs to integrate your burndown chart, seems to want it finished within 3 PM today (as he notified in Discord) so that he can continue his work.

I would advise you to fix the basic minimum feature, which is the "days" view, first before doing your "extra" features.

**Comment by Jangsoodlor** [comment]
It seems that it has finally rendered the dates correctly. Good Job! Overall, the burndown chart is serviceable.

However, there are still issues. First of all, the "9999 years" bug is still not fixed yet. As you can see, my browser is literally begging for life. It seems like your JS is loading a lot of objects in the background. This is an edge case, but can still happen nonetheless.
image
If you cannot fix it in JavaScript, you could try @BioB3 's solution, which is to implement query parameters.

Other than that, there's a small issue when the task is created one month after today still showing in the checkboxes. As you can see "😭😭😭😭" and "newer" are selected but are not shown in the burndown chart.
image

I'm thinking about whether or not should I approve this PR. On one hand, it works. On the other hand, it does not handle edge cases yet.

**Comment by KhunakornP** [comment]
> It seems that it has finally rendered the dates correctly. Good Job! Overall, the burndown chart is serviceable.
> 
> However, there are still issues. First of all, the "9999 years" bug is still not fixed yet. As you can see, my browser is literally begging for life. It seems like your JS is loading a lot of objects in the background. This is an edge case, but can still happen nonetheless. image If you cannot fix it in JavaScript, you could try @BioB3 's solution, which is to implement query parameters.
> 
> Other than that, there's a small issue when the task is created one month after today still showing in the checkboxes. As you can see "😭😭😭😭" and "newer" are selected but are not shown in the burndown chart. image
> 
> I'm thinking about whether or not should I approve this PR. On one hand, it works and Timmy seems to want it quick. On the other hand, it does not handle edge cases yet. Which is normally my standard when approving other people's PR

Truly unfortunate, It would appear the burndown chart is not done yet. Well, no matter you'd tried your best so I think it is only fitting that you take a break. I'll handle things from here.

**Comment by ErikLupical** [comment]
> > It seems that it has finally rendered the dates correctly. Good Job! Overall, the burndown chart is serviceable.
> > However, there are still issues. First of all, the "9999 years" bug is still not fixed yet. As you can see, my browser is literally begging for life. It seems like your JS is loading a lot of objects in the background. This is an edge case, but can still happen nonetheless. image If you cannot fix it in JavaScript, you could try @BioB3 's solution, which is to implement query parameters.
> > Other than that, there's a small issue when the task is created one month after today still showing in the checkboxes. As you can see "😭😭😭😭" and "newer" are selected but are not shown in the burndown chart. image
> > I'm thinking about whether or not should I approve this PR. On one hand, it works and Timmy seems to want it quick. On the other hand, it does not handle edge cases yet. Which is normally my standard when approving other people's PR
> 
> Truly unfortunate, It would appear the burndown chart is not done yet. Well, no matter you'd tried your best so I think it is only fitting that you take a break. I'll handle things from here.

Okay. If you have any questions about the code, you can ask me. I can explain how the code should function.

**Comment by KhunakornP** [comment]
> > > It seems that it has finally rendered the dates correctly. Good Job! Overall, the burndown chart is serviceable.
> > > However, there are still issues. First of all, the "9999 years" bug is still not fixed yet. As you can see, my browser is literally begging for life. It seems like your JS is loading a lot of objects in the background. This is an edge case, but can still happen nonetheless. image If you cannot fix it in JavaScript, you could try @BioB3 's solution, which is to implement query parameters.
> > > Other than that, there's a small issue when the task is created one month after today still showing in the checkboxes. As you can see "😭😭😭😭" and "newer" are selected but are not shown in the burndown chart. image
> > > I'm thinking about whether or not should I approve this PR. On one hand, it works and Timmy seems to want it quick. On the other hand, it does not handle edge cases yet. Which is normally my standard when approving other people's PR
> > 
> > 
> > Truly unfortunate, It would appear the burndown chart is not done yet. Well, no matter you'd tried your best so I think it is only fitting that you take a break. I'll handle things from here.
> 
> Okay. If you have any questions about the code, you can ask me. I can explain how the code should function.

If you actually wrote good code I will not have to ask you (Program Intently and Expressively). Also SHOULD function? Did you mean how it actually functions? Or did you not actually write the code yourself.

**Comment by KhunakornP** [comment]
This PR has gone on for far too long. I will be closing it now.

**Pull request closed without merging**
