### PR TITLE
Add a profile setting page

### PR DESCRIPTION
**Pull request by BioB3**
Issues:
- [x] #152 
- [x] #155 
- [x] #156 
- [x] #157 
- [x] #159 

Note:
- Don't forget to migrate since a field is changed.
- There's no permission / user info manangement, you have to do those on the admin site in order to test everything.
-  The above features (permission/info) are in another branch already, so I'm not implementing them here.
- The current calculator link is `https://www.google.com` because the calculator is in another branch.

### CODE REVIEW

**Comment by Jangsoodlor** [comment]
"profile" in lower case is kinda inconsistent with "Log Out" in camel case.
image

**Comment by BioB3** [comment]
FYI, that's not camel case, it's not even considered to be in any case because there is a space between `Log` and `Out`. You should use the word `Capitalize` instead but I'll update it.

**Review by Jangsoodlor — APPROVED** [review]
Everything is working as intended.

**Review by KhunakornP — CHANGES_REQUESTED** [review]
Every thing looks good, but you seem to have forgotten to add a default incase a parent has no children registered yet
no default

**Comment by KhunakornP** [comment]
Also, not sure why but somehow the calendar page is just gone when I changed my name
um

ok

**Comment by BioB3** [comment]
The page now looks like this when the parent has no children.

image

**Comment by BioB3** [comment]
As for the calendar not loading, from the console, it appeared that your browser somehow could not import getErrorDiv function because utils.js did not export the function. But the function is definitely there because it is from #148, and I did not make any change to JS files.

image

As for your description of the problem, I followed what you did and everything is working normally so I can't fix it because I can't reproduce it.

image

**Review by KhunakornP — APPROVED** [review]
Alright, default text looks good. good job!

**Pull request merged**
