### PR TITLE
Enhancements and Bugfix to Taskboard Frontend

### PR DESCRIPTION
**Pull request by Jangsoodlor**
TO BE DONE IN ITERATION 5.

### Taskboard page
- [x] Show the deadline in task cards on the taskboard page
- [x] Add a button to link the taskboard to the burndown chart
- [x] change card colour when the task is near the deadline
- [x] Add current status to task detail

### Taskboard Index page
- [x] Make the Modal disappear after the user creates a taskboard on the Taskboard Index page.

Also while working on it, I've refactored some duplicate codes.

### CODE REVIEW

**Review by KhunakornP — APPROVED** [review]
Overall, I like the redesign of the taskboard but I would like to add some suggestions.

- In 'utils.js' maybe add a function for when a deadline is very close (1 day, 6 hours ect.)
- A checkbox in task creation to toggle whether the modal should close after creating task

Going to approve this PR since the new features work but just leaving these suggestions here.

**Review by BioB3 — CHANGES_REQUESTED** [review]
Adding status to task details is fine, but you forgot to remove the plain-text class from the `select` element, resulting in an inconsistent style. Also, the small buttons look very weird. Could you make them extend across the viewport width?

In `utils.js`, constant `MinuteToMillisecond` and `MillisecondToDay` are in Pascal case, not Camel case as agreed in the style guide.

image

image

**Comment by BioB3** [comment]
Also, this image fits what you did.

image

**Comment by BioB3** [comment]
@KhunakornP suggests that we use ALL_CAPS case for "fixed" constant, so if you agree to do so, please let me know, I'll update the style guide.

``` js
const MINUTE_TO_MILLISECOND;
const MILLISECOND_TO_DAY;
```

**Comment by Jangsoodlor** [comment]
> @KhunakornP suggests that we use ALL_CAPS case for "fixed" constant, so if you agree to do so, please let me know, I'll update the style guide.
> 
> ```js
> const MINUTE_TO_MILLISECOND;
> const MILLISECOND_TO_DAY;
> ```

Yeah I kinda agree on that because it differentiates itself from normal "constant".

**Comment by BioB3** [comment]
I don't see anymore problem,

**Pull request merged**
