### PR TITLE
Setup API router and some ViewSets

### PR DESCRIPTION
**Pull request by BioB3**
A DefaultRouter is created as well as ViewSets for Taskboard, Task, and Event.
The API root can be accessed by going to `/api/`.

### CODE REVIEW

**Comment by BioB3** [comment]
tests will be added later

**Comment by Jangsoodlor** [comment]
While we're reformatting tests, I think it's an auspicious occasion to move `create_task` and `create_taskboard` to a separate file since those two functions are used a lot.

Also, the main page (`manager/taskboard`) is still broken (for now). I'm currently working on fixing that in `feature/taskboard` branch. To avoid working on the same thing twice, I will open the pull request shortly after all the tests of this branch are fixed.

**Comment by Jangsoodlor** [comment]
Also @ErikLupical @KhunakornP pls don't forget to review since we don't wanna review our own branch.

**Review by KhunakornP — APPROVED** [review]
Code looks good to me, but don't forget to add some tests for "errors" and "exceptions" for when resources are not found.

**Review by ErikLupical — APPROVED** [review]

**Pull request merged**
