### PR TITLE
Feature/google authentication

### PR DESCRIPTION
**Pull request by KhunakornP**
Add Google authentication to base template, again.

### CODE REVIEW

**Comment by KhunakornP** [comment]
I've changed the user login so that the user can change between google accounts without needing to sign out of the browser (reauthentication), I will be working on modifying the User model to differentiate between Students, A level examinees and Parents.

**Comment by KhunakornP** [comment]
The code is currently deployable though it does not do much right now. Also due to how the allauth was configured we might have to figure out a way to hide (or at least let the user gain it through github secrets) the client_id and secret.

**Review by BioB3 — APPROVED** [review]
Looks fine, the second login no longer loads the google account automatically.

**Review by Jangsoodlor — APPROVED** [review]
Seems fine to me. The different user models can be implemented later since we've agreed to make smaller pull requests in the last retrospective.

**Pull request merged**
