### PR TITLE
Enhancement to Calendar based on Code Review 11/1/2024

### PR DESCRIPTION
**Pull request by BioB3**
Issues
- [x] Update docstrings of TaskViewSet and EventViewSet
#117 
- [x] Remove add event button and show event creation modal after selecting date range
#137 
- [x] Add a help modal to show information about features on the calendar page
#138

### CODE REVIEW

**Review by KhunakornP — APPROVED** [review]
All features work as intended. Though one minor change I would like to suggest is make the help modal for the calendar quit when you click off it because currently it requires you to explicitly click the quit button which is inconsistent with other modals on the page.

**Comment by BioB3** [comment]
> All features work as intended. Though one minor change I would like to suggest is make the help modal for the calendar quit when you click off it because currently it requires you to explicitly click the quit button which is inconsistent with other modals on the page.

I'll update the modal tomorrow.

**Comment by Jangsoodlor** [comment]
I agree with KhunakornP.

**Review by Jangsoodlor — APPROVED** [review]
Everything is working as intended.

**Comment by BioB3** [comment]
I'm not merging this unless @KhunakornP re-reviews this because I applied a change he suggested.

**Review by KhunakornP — APPROVED** [review]
Looks good to me!

**Pull request merged**
