### PR TITLE
Initialize default files

### PR DESCRIPTION
**Pull request by KhunakornP**
Initialized base django app files and added requirements.txt and the iteration1 domain diagram for the wiki

### CODE REVIEW

**Comment by KhunakornP** [comment]
Not finished yet since ruff is complaining about missing models, views, and tests. For now please check the domain diagram

**Comment by BioB3** [comment]
The task model doesn't really need a start date, a deadline should be enough.

**Comment by Jangsoodlor** [comment]
There's also going to be Task Groups, which is a Group of tasks that will be used to calculate Burndown Velocity.

**Comment by KhunakornP** [comment]
We will be modifying the models when we implement the other features. For the first few iterations I think we should focus on the core features first, being the task board and calendar.

**Comment by KhunakornP** [comment]
I have created the starting templates for the manager app (the A-level calculator will be a separate app). Please check them and I will merge the files to main if no issues are found.

**Comment by Jangsoodlor** [comment]
> The task model doesn't really need a start date, a deadline should be enough.
we'll eventually need to add that anyways

**Review by Jangsoodlor — APPROVED** [review]
seems good to me

**Review by BioB3 — APPROVED** [review]
Everything looks fine.

**Pull request merged**
