### PR TITLE
Taskboard Improvement

### LINKED ISSUE #177: Excessively large text in taskboard name incorrectly handled by the application.
##**Bug or Defect**
Excessively large text in taskboard name incorrectly handled by the application.
I tried this given input, and I cannot create the taskboard as the application gave the error of `Taskboard name cannot be blanked.`

``` https://a-plus-management.onrender.com/manager/taskboard/https://a-plus-management.onrender.com/manager/taskboard/https://a-plus-management.onrender.com/manager/taskboard/https://a-plus-management.onrender.com/manager/taskboard/https://a-plus-management.onrender.com/manager/taskboard/https://a-plus-management.onrender.com/manager/taskboard/https://a-plus-management.onrender.com/manager/taskboard/https://a-plus-management.onrender.com/manager/taskboard/https://a-plus-management.onrender.com/manager/taskboard/https://a-plus-management.onrender.com/manager/taskboard/https://a-plus-management.onrender.com/manager/taskboard/https://a-plus-management.onrender.com/manager/taskboard/https://a-plus-management.onrender.com/manager/taskboard/https://a-plus ```
more lines omitted...

## **How To Reproduce**
1. Go to  'Taskboard' page
2. Click on 'Create a taskboard'
3. In the taskboard name field, input an extremely long text string (e.g., 1,000 characters or more)
4. Click on 'Create' button
5. The system incorrectly displays an error message stating that the field is blank, and the taskboard cannot be created.

**Expected behavior**
The taskboard name should have a character limit. The error message should accurately indicate the issue (e.g., "Taskboard name exceeds the character limit").

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: [Window11
 - Browser: Chrome
 - Version: 23

### PR DESCRIPTION
**Pull request by Jangsoodlor**
fix #177 and #181

### CODE REVIEW

**Review by BioB3 — APPROVED** [review]
The offcanvas closes as suggested in issues, as for the taskboard name input, the limit on characters is reasonable.

**Review by KhunakornP — CHANGES_REQUESTED** [review]
The changes work as expected but can you also add the title limit to tasks as well? as mentioned in #178

**Comment by KhunakornP** [comment]
Also, I found an appearance issue where finished tasks are still highlighted the same as tasks near the deadline. Could you also change the border for the finished tasks?

**Review by KhunakornP — APPROVED** [review]
The requested changes are added and works! good job.

**Pull request merged**
