### PR TITLE
Added calendar page that shows the tasks and events that are in a given month

### PR DESCRIPTION
**Pull request by ErikLupical**

### CODE REVIEW

**Review by Jangsoodlor — CHANGES_REQUESTED** [review]
There are a few problems in your `calendar.html` file.
- The `<body>` syntax does not have its closing syntax </body>
- You have the closing syntax `</head>` but did not have its opening syntax
- And the calendar itself does not even load
error

**Review by KhunakornP — CHANGES_REQUESTED** [review]
- in line 74 in `views.py` please remove the main block.
- in `settings.py` please uncomment the python decouple config and remove `DEBUG = True`
- in `views.py` please change the hardcoded redirect URL to a dynamic URL
-  please add unittests for your code and ensure that they pass

**Comment by KhunakornP** [comment]
> * in line 74 in `views.py` please remove the main block.
> * in `settings.py` please uncomment the python decouple config and remove `DEBUG = True`
> * in `views.py` please change the hardcoded render URL to a dynamic URL
> * please add unittests for your code and ensure that they pass

BEFORE you do all these things however please approve the branches for event and task views and fetch the changes from main since you copied directly from the pull request you dont have migrations yet which is why the calendar is breaking in @Jangsoodlor review

**Comment by KhunakornP** [comment]
Also, DO NOT COMMIT MIGRATION FILES! since the branch did not merge from `feature/events` which has migrations if new migration files are committed the migrations may break.

**Comment by Jangsoodlor** [comment]
The code is now working, but there's a small visual bug here. In months where the first day of the week is Sunday, there seems to be a blank row on the top of the calendar.
image

**Review by BioB3 — CHANGES_REQUESTED** [review]
- Please remove the `</head>` and `<body>` tags in `calendar.html` (lines 10 and 11) because they shouldn't be there. The template `base.html` already has those tags and by having multiple elements of them, the page may not load properly according to [this](https://stackoverflow.com/questions/2603133/is-it-ok-to-have-multiple-html-head-and-body-elements-in-single-page).
- I get this warning message every time I load a calendar page of a month and year I haven't been to. You can fix this later so focus on fixing other ones.
image
- You should extract the style in `calendar.html` (line 107) and put it in `calendar.css` especially when the page is already loading the CSS file, as for the reason you can check [this](https://stackoverflow.com/questions/9832513/when-to-style-directly-in-the-html-instead-of-css).
image
- Please delete or update the comments for colours in `calendar.css` because some of them are just blatantly wrong.
image
image
image
image
image

**Comment by KhunakornP** [comment]
> * I get this warning message every time I load a calendar page of a month and year I haven't been to. You can fix this later so focus on fixing other ones.
I think this is an issue with how the `today_midnight()` is currently modeled since it uses `.replace()` which removes the localtime support of django's `timezone` object. I think to fix this you just have to convert the `datetime` to one with localtime

**Comment by KhunakornP** [comment]
> > * I get this warning message every time I load a calendar page of a month and year I haven't been to. You can fix this later so focus on fixing other ones.
> 
> I think this is an issue with how the `today_midnight()` is currently modeled since it uses `.replace()` which removes the localtime support of django's `timezone` object. I think to fix this you just have to convert the `datetime` to one with localtime

actually scratch that its an issue with the event dates which does not use `today_midnight()` so the problem must be with how the events were originally created.

**Comment by BioB3** [comment]
> Reference in new

Yes, it is stated in the warning message that `Event.start_date` received a "naive datetime" while `timezone` is available and that's all this message is about.

**Comment by KhunakornP** [comment]
Um, It would appear that in your `models.py` Events have an associated task board which is clearly wrong please delete the task board field.

**Comment by BioB3** [comment]
We have agreed to let me take over implementing this feature, so I'll close this pull request and open a new one after I've done revising the calendar. Most changes here will be removed because I planned on using [Fullcalendar](https://fullcalendar.io/) API.

**Pull request closed without merging**
