### PR TITLE
Feature/authentication user info

### PR DESCRIPTION
**Pull request by KhunakornP**
Extended the User class to include more information. The reason for the new models is for SRP principle since the User class should only concern about Authentication and not store user data.

### CODE REVIEW

**Comment by KhunakornP** [comment]
Somehow the ruff path on my main pc is wrong. I will lint the code later. For now please check out the code.

**Comment by KhunakornP** [comment]
I have updated the code so that all Users are Students by default upon User creation (Users can change it later.). I have also updated the tests to reflect the change.

**Comment by KhunakornP** [comment]
I do you think we should update the models to track which User created it before or after we remodel our backend to use REST API? I will be doing it in a separate branch but I am asking this so that I can prioritize my work correctly.

**Comment by KhunakornP** [comment]
SIDE NOTE: expect the docs/config-google-oauth-instructions branch tonight.

**Comment by BioB3** [comment]
Putting it as a new file should be better, you could link to it in the `installation.md` or readme

**Comment by KhunakornP** [comment]
Alright, but please dont forget to review the pull request.

**Review by BioB3 — APPROVED** [review]
The new models seem fine, don't forget to update the branch after PR #62 is closed.

**Review by Jangsoodlor — APPROVED** [review]
seems fine by me

**Pull request merged**
