### PR TITLE
Add taskboard functionality

### PR DESCRIPTION
**Pull request by Jangsoodlor**
- Add views to handle Task and Taskboard creation, modification and deletion
- Add HTML front-end for taskboard and taskboard index pages
- Add type hints to views and models

### CODE REVIEW

**Review by KhunakornP — APPROVED** [review]
Overall, the code looks fine but I had an issue with the drag and drop feature. You could fix it now or make a bugfix branch and I think that's fine as well. Also I really really think that adding typehints for the Model classes is really overkill especially if you use something like model.CharField when it's literally right there.

**Comment by KhunakornP** [comment]
> Overall, the code looks fine but I had an issue with the drag and drop feature. You could fix it now or make a bugfix branch and I think that's fine as well. Also I really really think that adding typehints for the Model classes is overkill especially if you hint it with something like model.CharField when it's literally right there.

UPDATE: It would seem that this is an issue if you don't have your DEBUG set to True in settings. Ensure you update your copy of .env to have DEBUG = True

**Review by ErikLupical — APPROVED** [review]
The models does not seem to conflict with calendar

**Comment by KhunakornP** [comment]
> The models does not seem to conflict with calendar

model? what model The main changes are the views and calendar page? if your worried that the typehints will break you calendar I don't know what to say, did you even read the changes?

**Pull request merged**
