### PR TITLE
Add input validation

### PR DESCRIPTION
**Pull request by BioB3**
Add input validation to existing pages (#96)
- [x] Task creation (#115)
- [x] Task update (#115)
- [x] Taskboard creation
- [x] Event creation
- [x] Event update

I forgot to create subtasks, sorry about that. 

image

### CODE REVIEW

**Review by Jangsoodlor — APPROVED** [review]
I've tested all the things you listed. All works fine. But inputting stuffs that violate model constraints cannot be check (e.g. taskboard title longer than 300 characters). But it's an edge case so we could do that in future iterations.

**Review by KhunakornP — CHANGES_REQUESTED** [review]
Issues:
- [x] When you add or update an event, If you set start date == end date exactly the event end date bugs out and defaults to 1/1/1970.
- [x] You can input negative estimated time in tasks.
- [ ] inputting a nonsense number (such as --111, or ++15) creates a task with estimated time of 0

Other features are working fine.
please revise the above issues.

**Comment by BioB3** [comment]
Those will be fixed pretty soon. I'm pretty sure I only need like 4 lines of code to fix them.

**Review by KhunakornP — APPROVED** [review]
All issues have been resolved. Good job!

**Pull request merged**
