### PR TITLE
Feature/parent dashboard

### PR DESCRIPTION
**Pull request by KhunakornP**
Features:

- [x]  Users can now choose their role upon logging in for the first time
- [x] Parents now have access to their students material
- [x] The parent dashboard can access students taskbords
- [ ] The parent dashboard can access student burndown charts
- [x] The parent dashboard provides a quick summary on students progress

will convert to PR once all features are done.

### CODE REVIEW

**Comment by KhunakornP** [comment]
## features
- Parents can see all their children on the main dashboard page
- Parents can see the status of their children's tasks on the main and chart index pages
- The chart index page lists all available taskboards of that child and also the recent velocity of the each taskboard
- When a user is first created they are brought to the setup page
- In the setup page the user can choose their roles

## notes
- Despite depending on the burndown chart I am putting this feature on review for early feedback
- The links to the burndown chart and velocity for the charts are places holders
  - this is due to the fact the the burndown chart is not done yet as of 11/20/2024 4:35 pm

**Comment by KhunakornP** [comment]
Codecov is screaming right now. I'll address this with more tests later

**Comment by Jangsoodlor** [comment]
- Parents can access A-Level Calculator even though they selected NOT taking a-level during registration.

**Comment by KhunakornP** [comment]
Yeah you can do that. I gave them access since while they may not take the A-levels. Maybe they have a child who takes it. And I don't want to loop through all the children to check so I just give them implicit access.

**Comment by Jangsoodlor** [comment]
One thing I just noticed is that the "Overview of taskboard progress" seems to be shared by multiple children. Is this intentional?
image
image
image

**Comment by Jangsoodlor** [comment]
The pie chart bug is still there!

**Comment by KhunakornP** [comment]
Ah, must have forgotten to fix it. I'll fix it right now

**Comment by KhunakornP** [comment]
It is fixed however I did have to explicitly write `get_context_data()` I don't know why the template was not picking up the path parameter so this is a "quick hack" of sorts but we can fix this later given our deadlines.

**Comment by BioB3** [comment]
When I clicked the `go to chart` button from a child's burndown charts, it redirected me to an undefined taskboard page.

image

Is this just a placeholder as the link to the chart itself is not ready?

**Comment by BioB3** [comment]
The URL redirected by clicking `Burndown Chart` Button in a child's taskboard is incorrect.
You have to remove /4 somehow I think.

image

**Review by Jangsoodlor — APPROVED** [review]
The bugs are fixed.

**Comment by KhunakornP** [comment]
> The URL redirected by clicking `Burndown Chart` Button in a child's taskboard is incorrect.
> You have to remove /4 somehow I think.
> 
> image

Gimme a few mins to finish my lunch. Should only need to edit the template.

**Comment by BioB3** [comment]
Alternatively you could straight up remove/disable both `add task` and `burndown chart` button if the parent is viewing the child's taskboard. They can go to the burndown chart page from the pie chart page anyways.

**Comment by KhunakornP** [comment]
> > The URL redirected by clicking `Burndown Chart` Button in a child's taskboard is incorrect.
> > You have to remove /4 somehow I think.
> 
> Gimme a few mins to finish my lunch. Should only need to edit the template.

In any case, If the burndown chart is done before 13:20 I'll add the links to both pages. If not I'll add an error message.

**Review by BioB3 — APPROVED** [review]
Aside from the burndown chart link issues, everything is working fine.

**Pull request merged**
