### PR TITLE
[render preview] Feature/burndown chart deploy

### PR DESCRIPTION
**Pull request by ErikLupical**

### CODE REVIEW

**Comment by KhunakornP** [comment]
I'm currently a bit busy, but I'll be sure to get the chart deployed by either today or tomorrow.

**Comment by BioB3** [comment]
Please resolve the merge conflicts, I don't think it is deployable yet without the deployment configuration currently in `main`.

**Comment by KhunakornP** [comment]
@ErikLupical I've resolved the merge conflicts and have setup a staging db for you to use. The credentials for the admin account are in your DM's. I've tried verifying the code and it seems to be giving an error about yMIN is not defined. Also, this version does not have a default message for when the taskboard has no data. Fix the mentioned issues and verify that the burndown chart is satisfactory notify me and I'll merge it to production.

**Comment by KhunakornP** [comment]
As for the test, That one's on me. I'll have it fixed.

**Pull request merged**
