### PR TITLE
Fix broken login sequence

### PR DESCRIPTION
**Pull request by KhunakornP**
- Login now actually redirects to the application
- The main login page now has messages (but somehow the background breaks but we redesign the UI later)

sorry-maam-my

### CODE REVIEW

**Review by Jangsoodlor — CHANGES_REQUESTED** [review]
There's a few problems in your `google_auth_setup_guide.md` file

- In `Set up your Google credentials`
  - Step 13: The redirect uri in the picture and the text does not match
  - Step 14: You misspelled `.evn`
 
- In `Set up the social application on the admin site`
  - Step 5: In the picture you put `your secret key here` in the picture. The user may confuse this with `SECRET_KEY` which is supposed to be `django.core.management.utils.get_random_secret_key`. NOT the secret key from Google. You may also consider replacing client id and secret with `CLIENT_ID` and `SECRET` in the written instructions to be more specific.

**Comment by BioB3** [comment]
I'll do the review after the above changes have been made.

**Review by Jangsoodlor — APPROVED** [review]
The instructions seems clear to me.

**Review by BioB3 — APPROVED** [review]
The redirect works correctly now, and the instruction has improved.

image

**Pull request merged**
