### PR TITLE
A-Level Calculator

### PR DESCRIPTION
**Pull request by Jangsoodlor**
Create a calculator page with the following features:
- [x] User can enter their score and save it in the database
- [x] User can select university, faculty, major, and criteria to load score weight
- [x] User can enter score weight manually as well
- [x] The calculation shows the correct computed score
- [x] Last year's data is loaded on the results page if a major and criteria are selected

Also update all views to require login, I didn't open a new branch because there is almost no time and I can not wait for other PR to be merged into `main`.

*Note:*
- You must login to use this
- The script to load data can be run by
```
pip install django-extensions
python manage.py runscript calculator.import_data
```

-- @BioB3 --

### CODE REVIEW

**Comment by KhunakornP** [comment]
do you perhaps have a data.json file available? Doesn't really matter since we populate the db anyways but would help with checking

**Comment by KhunakornP** [comment]
OK despite not populating the db with the exams I have found a few issues.
- There does not seem to be a check for GPAX at all. User can type whatever he wants.
- The calculator does not seem to consider GPAX as a possible criteria. (some majors do actually use raw GPAX)
gpax w

- you can manually go to the last page of the calculator (minor nitpick, maybe have a redirect or default text?)
- The myTcas link is just www.google.com instead of a link to the major.

**Comment by KhunakornP** [comment]
> OK despite not populating the db with the exams I have found a few issues.
> 
> * There does not seem to be a check for GPAX at all. User can type whatever he wants.
> * The calculator does not seem to consider GPAX as a possible criteria. (some majors do actually use only raw GPAX)
> 
> gpax w
> 
> * you can manually go to the last page of the calculator (minor nitpick, maybe have a redirect or default text?)
> * The myTcas link is just [www.google.com](http://www.google.com) instead of a link to the major.

Upon further inspection this is probably because GPAX is directly hard coded into the template. Also there seems to be TODO sections in `exam_weight_fields.js`

**Comment by BioB3** [comment]
All of the problems you stated except GPAX are because you don't have any exam, university, faculty, major and criteria data. Once the user has computed the score, it is saved in the session, and the major they last calculated as well, so when they directly access the page, everything is loaded. The google link is a placeholder which I don't know why @Jangsoodlor did it.

**Comment by BioB3** [comment]
Unless you really want me to add cases when there is no data at all, which is very unlikely assuming we did write a script to read data from csv.

**Comment by Jangsoodlor** [comment]
GPAX "Exam" can be created by:
`Exams.objects.create(name="GPAX", max_score=4, core=False)`

**Review by ErikLupical — APPROVED** [review]
I don't exactly know how mytcas works and it's also in Thai but it didn't seem to encounter any errors

**Review by KhunakornP — CHANGES_REQUESTED** [review]
Overall the calculator works but I would like to ask for a previous button for the calculator. Incase the user clicks a major but hasn't inputted all the relevant fields in the score card. Also, can you show the score weights on the results page as well? since we kinda cut the descriptive statistics I think that showing the user the data would at least help them verify the results.

**Comment by BioB3** [comment]
In my opinion, the score weight can already be accessed by going to the myTCAS link on the results page unless they input the weight manually which would result in no major after redirecting.

**Review by KhunakornP — APPROVED** [review]
Buttons work and overall the calculator looks good to me. Good job!

**Pull request merged**
