### PR TITLE
Create codecov.yml

### PR DESCRIPTION
**Pull request by KhunakornP**
Testing codecov CI nothing to review yet

### CODE REVIEW

**Comment by KhunakornP** [comment]
Hopefully, in new pull requests the codecov bot should generate a coverage report in the PR.

**Comment by KhunakornP** [comment]
CI is now ready please review it when you are free.

**Comment by BioB3** [comment]
The badge looks good and since the Codecov bot is here, I'm sure this works correctly.

**Review by BioB3 — APPROVED** [review]

**Review by Jangsoodlor — APPROVED** [review]
Seems fine by me. Technically, the codecov badge should change from `unknown` to the actual percentage after it's merged into main right?

And I think */*/directory is unneccessary according to [the docs](https://github.com/KhunakornP/A-plus-management/issues/48)

**Pull request merged**
