### PR TITLE
[render preview] Setup deployment

### PR DESCRIPTION
**Pull request by KhunakornP**
testing the new deployment configurations

### CODE REVIEW

**Review by Jangsoodlor — APPROVED** [review]
It works and the data stays there. Good job!

**Review by BioB3 — APPROVED** [review]
The deployment works, I can log in with my accounts and access the site's functionality. I also want #149 to be included because the profile page for parents and the parent list for students are left unused, but it's fine since the burndown chart is not finished.

**Comment by KhunakornP** [comment]
> The deployment works, I can log in with my accounts and access the site's functionality. I also want #149 to be included because the profile page for parents and the parent list for students are left unused, but it's fine since the burndown chart is not finished.

I will merge that as well, If the burndown chart has no pending updates by 20:30. I will go fork the velocity API from #165 and add error messages to the chart links.

**Comment by KhunakornP** [comment]
For anyone who's looking at this. The absolute non-negotiable, non-delayable deadline to get approval for the first deployment is 22:30. If you do not have approval by then you can still add the feature HOWEVER since we have deployed the app the checks will be even more strict.

**Pull request merged**
