### PR TITLE
docs/installation-guide

### PR DESCRIPTION
**Pull request by KhunakornP**
Added more sections to the readme and added CI badges, added Installation.md

### CODE REVIEW

**Review by Jangsoodlor — CHANGES_REQUESTED** [review]
In `Installation.md`

2. change the directory to the ku-polls directory
```
cd ku-polls
```

pls fix

**Comment by BioB3** [comment]
On step 4 in `installation.md`, you should add another comment for the first command as well.

**Review by BioB3 — APPROVED** [review]
Everything looks correct to me.

**Review by Jangsoodlor — APPROVED** [review]
seems fine by me
img

**Pull request merged**
