### PR TITLE
Feature/restful burndown chart

### PR DESCRIPTION
**Pull request by ErikLupical**
In the burndown chart:
- [x] If there are no estimate history objects, the page will tell user to create tasks on taskboard.
- [x] The chart shows the chart with the estimate history filled between days.
- [x] The tasks between today and the estimated end date will be annotated and can be toggled by the checkboxes
- [ ] If there is only one estimate history object, or if the estimate history with the latest date has the highest time remaining, the chart will try to use average velocity. The user will be informed that there is not enough data to estimate velocity.

### CODE REVIEW

**Comment by KhunakornP** [comment]
Yknow, 1 out of 4 tasks does not seem very "basically finished to me". Also, I see that you expect that a chart with one estimate history object will somehow produce a velocity when on average (spoilers 0 divided by anything is still 0).

**Comment by KhunakornP** [comment]
I also see that for the past 2 days, no changes were made to the charts presentation at all. If the chart was already done why didn't you pull request sooner?

**Comment by Jangsoodlor** [comment]
pls fix failing tests.

**Comment by BioB3** [comment]
I think the date view looks fine, but the week and month view look off.

image
image

Can you make the velocity line a normal line instead of a dashed line? I don't know what you would get from dashed line, it is hard to notice.

**Comment by KhunakornP** [comment]
> I think the date view looks fine, but the week and month view look off.
> ...
> Can you make the velocity line a normal line instead of a dashed line? I don't know what you would get from dashed line, it is hard to notice.

btw are you sure your calling the week velocity? It should not be the same as month

**Comment by KhunakornP** [comment]
Also
chart

I'm pretty sure you know why this is wrong

**Comment by ErikLupical** [comment]
> wrong

How to recreate?

**Comment by Jangsoodlor** [comment]
image
Is this supposed to be working product?

**Pull request closed without merging**
