### PR TITLE
Add basic outline of what burndown chart page should look like

### PR DESCRIPTION
**Pull request by Jangsoodlor**
- Add a basic HTML file for the burndown chart page
- Modify display_burndown_chart to a class-based view that can handle both get and post request
- The events are just dummy events for now
- Most of the work probably needs to be replaced once we switch to REST API anyway but I want to merge first to at least save the progress before refractoring.

### CODE REVIEW

**Comment by BioB3** [comment]
Everything looks fine, but please update the branch, so I'm sure that you won't do funny things while merging.

**Review by KhunakornP — APPROVED** [review]
Looks fine to me!

**Comment by KhunakornP** [comment]
> Everything looks fine, but please update the branch, so I'm sure that you won't do funny things while merging.

btw you cant merge if your branch is out of date anyways, but good on ya for reminding.

**Comment by Jangsoodlor** [comment]
branch updated

**Review by BioB3 — APPROVED** [review]
Everything looks ok.

**Pull request merged**
