### PR TITLE
Feature/object ownership

### PR DESCRIPTION
**Pull request by KhunakornP**
- Objects such as Task and Events are now shown only to the User that created them
- Object models now store User as a field
- Added a basic login page

### CODE REVIEW

**Comment by KhunakornP** [comment]
my bad forgot to update the tests

**Comment by BioB3** [comment]
taskboard and task deletion are not possible, I received 403 status from the request.

**Review by BioB3 — APPROVED** [review]
Everything works the same as before, with the exception of not being able to see other accounts' information. Also, you should update the Google OAuth guide, but there is nothing wrong with the program.

**Comment by Jangsoodlor** [comment]
seems fine by me.

**Review by Jangsoodlor — APPROVED** [review]
seems fine by me.

**Comment by KhunakornP** [comment]
I'll update the docs later

**Pull request merged**
